# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  #--------------set hostname and sync folder, setup puppet------#
  config.vm.hostname = 'vagrant-test'
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.puppet_install.puppet_version = :latest 
  config.vm.provision :puppet

  #------------ditital_ocean's config-------------#
  config.vm.provider :digital_ocean do |provider, override|
  override.ssh.private_key_path = '~/.ssh/id_rsa'
  override.vm.box = 'digital_ocean'
  override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

  provider.token = 'Token here..'  
  provider.image = 'ubuntu-14-04-x64'
  provider.region = 'nyc1'
  provider.size = '512mb'
  provider.setup = false

  end

    #application server
    config.vm.define "appserver" do |vm1|
       vm1.vm.hostname = "appserver"
    end

    #database server
    config.vm.define "dbserver" do |vm2|
        vm2.vm.hostname = "dbserver"
    end

    #--------------puppet provision's file location------#
    config.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "proservers.pp"
    end
  
end
